### PR TITLE
Add simple API call

### LINKED ISSUE #448: Calling the `demucs/separate.py` script from another python file
## ❓ Questions

Hi, y'all. Thanks for creating and maintaining this amazing library. 🙂 

I'm new to this package. I'm writing a python code that, in one of its steps, will perform the source separation task with demucs.

From the documentation, I've read the usage of the source separation utility is by the CLI program.

My questions are:
- By calling the source separation utility from a python script, the correct way to do it is by calling the CLI directly like below?
```python
 import subprocess;
 subprocess.run("demucs PATH_TO_AUDIO_FILE_1 [PATH_TO_AUDIO_FILE_2 ...]")
```
- by reading the `demucs/separate.py` file, I've seen the CLI program basically calls the `load_track(...)` and the `apply_model(...)` functions, with some logic attached to the main program related to the arguments. Is there a "python function interface" that does something similar with the source separation task in demucs?

Thanks :)

### LINKED ISSUE #450: a
a

### LINKED ISSUE #472: Python API?
# ❓How do I use demucs in Python directly?

I'm trying to run demucs as part of my python programme. 

Apologies if this seems naive but try as I might I can't find out how to use demucs from python directly. I have the pip package installed ok (I think) but it's literally as simple as me not knowing how to call the methods. Normally when you've installed a python package the autocomplete methods provide guidance for what the methods are but `demucs` doesn't. 

For example this doesn't work -- the `separate` method isn't found. nor is `separate_into_files` etc etc. 

```
from demucs import demucs 
demucs.separate(input_filename, sources=['vocals'], out_dir='output', suffix='vocals')
```
with error
`separate: unknown`

Alternatively I tried
```
from demucs import demucs
model = demucs.Demucs('demucs', 2)
model.separate(input_filename, sources=['vocals'], out_dir='output', suffix='vocals')

```

with error `AttributeError: 'Demucs' object has no attribute 'separate'`

### PR DESCRIPTION
**Pull request by CarlGao4**
Close #472, close #450, close #448

### CODE REVIEW

**Comment by adefossez** [comment]
Thanks a lot @CarlGao4, we could make a nicer looking API but that is a good start for now :)

**Comment by CarlGao4** [comment]
> Thanks a lot @CarlGao4, we could make a nicer looking API but that is a good start for now :)

As you can see on my fork, it is still under development :)
I will finish it in one or two days, so please just wait for a while to avoid conflict or duplication, thx

**Comment by boxabirds** [comment]
Great! How do I get access to this build? The default repositories still appear to have a previous build (where `main()` has no parameters).

**Comment by CarlGao4** [comment]
@boxabirds I've added a few more complex API functions and you can see it at [CarlGao4/demucs](https://github.com/CarlGao4/demucs)
Docs available at [CarlGao4/demucs/docs/api.md](https://github.com/CarlGao4/demucs/blob/main/docs/api.md)

To install it, please run this command: `python3 -m pip install -U git+https://github.com/CarlGao4/demucs#egg=demucs`

Make sure that you have git installed.

**Pull request merged**
