### PR TITLE
Changes to Famzah/main PR 244

### PR DESCRIPTION
**Pull request by adefossez**
this is some fixes to the code provided by @famzah : https://github.com/facebookresearch/demucs/pull/244

### CODE REVIEW

**Comment by famzah** [comment]
You did well by splitting the sub-model load into the GPU, too!

There is one thing in "separate.py" [Line 116](https://github.com/facebookresearch/demucs/blob/3e5ea549ba921316c587e5f03c0afc0be47a0ced/demucs/separate.py#L116) which seem incorrect:
```python
        wav = load_track(track, args.device, model.audio_channels, model.samplerate)
        wav = wav.cpu()
```

This unconditional `wav = wav.cpu()` should be removed. Instead we should provide `"cpu"` where we provide "args.device":
```python
wav = load_track(track, "cpu", model.audio_channels, model.samplerate)
```

Without the fix, the workflow with a very long track would be:
1. Load the very long track into the GPU. This requires a lot of memory, and we may run out of the limited amount of GPU memory.
2. Move the model out of the GPU into CPU RAM. The whole operation into the GPU was in vain.

**Comment by adefossez** [comment]
I did it so that the resampling of the audio happens on GPU. This can take a non negligible amount of time if the track is long, although I haven't measured it.

**Comment by famzah** [comment]
I've benchmarked this and to my surprise, it's faster if we do it directly in the CPU. The test track is 136 minutes long. Here are the results:
- with the current implementation (load in the GPU, then transfer to the CPU):
```
load_track(): 9.619 seconds
wav.cpu(): 2.548 seconds
```
- if we provide "cpu" for "args.device" and then skip wav.cpu():
```
load_track(dev=cpu): 9.041 seconds
```

About 8-10 CPU cores were briefly utilized during this initialization stage but I haven't measured exactly which stage benefits from multiple CPUs.

@adefossez, do you want me to open another PR only for this change, or you can push this upstream directly? Only if you agree with the idea, of course.

**Comment by adefossez** [comment]
What was the sample rate of the track ? It would be good to do the same with a track whose sample rate is different from the one of the model (44100), for instance 48000, as then the resampling should be much faster on gpu.

**Comment by famzah** [comment]
48000, 24-bit, size is 1.09 GB. I can provide the track for your own tests, if you need it.

**Comment by adefossez** [comment]
Ah cool ! Okay we can change that then

**Comment by famzah** [comment]
I now remembered to note that the file is mono (not stereo). If you want, next week(s) when I have the opportunity, I can test with a stereo file, too.

**Comment by adefossez** [comment]
It shouldn't change much don't worry.

**Comment by adefossez** [comment]
ive switched back to loading the track on CPU, I had to push a new version to pypi anyway because of a bug I had introduced.

**Pull request merged**
