### PR TITLE
fix segment fail using single model and add maximum version for pytorch

### PR DESCRIPTION
**Pull request by CarlGao4**

### CODE REVIEW

**Comment by CarlGao4** [comment]
Please see the log of GitHub Action. You can see the error before I added torch<1.12
But after I added that, the error was fixed.

**Comment by adefossez** [comment]
I'm reluctant to stop following PyTorch version, unless we understand what is causing the issue. At least on one machine it was working with 1.12. I'm on vacation so I don't have my laptop I will look into it next week when I get back.

**Comment by adefossez** [comment]
I have fixed the incompatiblities with the new torch and torchaudio. Can you update your PR to remove the changes to the requirements? Thanks :)

**Review by CarlGao4 — COMMENTED** [review]
version requirement for torch removed.

**Comment by adefossez** [comment]
Thanks a lot for the fixes!

**Pull request merged**
